# Inspect the executable and deployed Qt plugins, and copy their dependency closure.
if(NOT EXISTS "${EXECUTABLE}")
    message(FATAL_ERROR "Executable not found: ${EXECUTABLE}")
endif()
get_filename_component(destination "${EXECUTABLE}" DIRECTORY)
string(REPLACE "|" ";" search_dirs "${SEARCH_DIRS}")
if(WIN32)
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM windows+pe)
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_TOOL "${RUNTIME_TOOL}")
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND "${OBJDUMP}")
endif()
if(WINDEPLOYQT)
    execute_process(COMMAND "${WINDEPLOYQT}" --no-translations "${EXECUTABLE}"
        RESULT_VARIABLE deploy_result)
    if(NOT deploy_result EQUAL 0)
        message(FATAL_ERROR "windeployqt failed: ${deploy_result}")
    endif()
endif()
file(GLOB_RECURSE plugins "${destination}/*.dll")
set(system_excludes)
if(WIN32)
    file(TO_CMAKE_PATH "$ENV{SystemRoot}" system_root)
    set(system_pattern "")
    string(LENGTH "${system_root}" system_length)
    math(EXPR last_index "${system_length} - 1")
    foreach(index RANGE 0 ${last_index})
        string(SUBSTRING "${system_root}" ${index} 1 character)
        if(character MATCHES "[A-Za-z]")
            string(TOLOWER "${character}" lower)
            string(TOUPPER "${character}" upper)
            string(APPEND system_pattern "[${lower}${upper}]")
        else()
            string(APPEND system_pattern "${character}")
        endif()
    endforeach()
    list(APPEND system_excludes "^${system_pattern}/.*")
endif()
file(GET_RUNTIME_DEPENDENCIES
    EXECUTABLES "${EXECUTABLE}"
    LIBRARIES ${plugins}
    DIRECTORIES ${search_dirs}
    PRE_EXCLUDE_REGEXES "[Aa][Pp][Ii]-[Mm][Ss]-.*" "[Ee][Xx][Tt]-[Mm][Ss]-.*"
    POST_EXCLUDE_REGEXES ${system_excludes}
    RESOLVED_DEPENDENCIES_VAR resolved
    UNRESOLVED_DEPENDENCIES_VAR unresolved
    CONFLICTING_DEPENDENCIES_PREFIX conflicts)
if(unresolved)
    message(FATAL_ERROR "Missing runtime DLLs for ${EXECUTABLE}: ${unresolved}. Search directories: ${search_dirs}")
endif()
if(conflicts_FILENAMES)
    message(FATAL_ERROR "Conflicting runtime DLLs: ${conflicts_FILENAMES}. Use the same compiler for Qt, OpenCV and the application.")
endif()
foreach(dependency IN LISTS resolved)
    get_filename_component(directory "${dependency}" DIRECTORY)
    if(NOT directory STREQUAL destination)
        execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different
            "${dependency}" "${destination}" RESULT_VARIABLE copy_result)
        if(NOT copy_result EQUAL 0)
            message(FATAL_ERROR "Cannot deploy ${dependency}")
        endif()
    endif()
endforeach()
message(STATUS "Runtime dependencies deployed: ${EXECUTABLE}")
